### YamlMime:UniversalReference
api_name: []
items:
- attributes: []
  children:
  - google.cloud.bigquery.dbapi.NotSupportedError.with_traceback
  class: google.cloud.bigquery.dbapi.NotSupportedError
  fullName: google.cloud.bigquery.dbapi.NotSupportedError
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - inheritance:
          - type: builtins.object
          type: builtins.BaseException
        type: builtins.Exception
      type: google.cloud.bigquery.dbapi.exceptions.Error
    type: google.cloud.bigquery.dbapi.exceptions.DatabaseError
  langs:
  - python
  module: google.cloud.bigquery.dbapi
  name: NotSupportedError
  source:
    id: NotSupportedError
    path: tests/testdata/gapic-combo/google/cloud/bigquery/dbapi/exceptions.py
    remote:
      branch: add_goldens
      path: tests/testdata/gapic-combo/google/cloud/bigquery/dbapi/exceptions.py
      repo: git@github.com:googleapis/sphinx-docfx-yaml.git
    startLine: 57
  summary: 'DB-API error for operations not supported by the database or API.


    '
  syntax: {}
  type: class
  uid: google.cloud.bigquery.dbapi.NotSupportedError
- attributes: []
  class: google.cloud.bigquery.dbapi.NotSupportedError
  fullName: google.cloud.bigquery.dbapi.NotSupportedError.with_traceback
  langs:
  - python
  module: google.cloud.bigquery.dbapi
  name: with_traceback
  source:
    id: with_traceback
    path: null
    remote:
      branch: add_goldens
      path: null
      repo: git@github.com:googleapis/sphinx-docfx-yaml.git
    startLine: null
  summary: 'Exception.with_traceback(tb) --

    set self.__traceback__ to tb and return self.


    '
  syntax: {}
  type: method
  uid: google.cloud.bigquery.dbapi.NotSupportedError.with_traceback
references:
- fullName: google.cloud.bigquery.dbapi.NotSupportedError.with_traceback
  isExternal: false
  name: with_traceback
  parent: google.cloud.bigquery.dbapi.NotSupportedError
  uid: google.cloud.bigquery.dbapi.NotSupportedError.with_traceback
